[theme]
primaryColor="#1976D2"  # A shade of blue (Material Design blue 500)
backgroundColor="#E3F2FD"  # A light blue background (Material Design blue 50)
secondaryBackgroundColor="#BBDEFB" # A slightly darker light blue (Material Design blue 200)
textColor="#212121"      # Dark gray text
font="sans serif"
